

input:
  kafka:
    addresses: [ "${REDPANDA_HOSTS}" ]
    topics:
      - keygen
    consumer_group: "redpanda-connect-keygen-mongo"

output:
  label: "mongokeygen"
  mongodb:
    url: #{MONGO_URL}# 
    username: "k8sstormcenterru" # No default (required)
    password: #{MONGO_PASSWORD}# 
    database: #{DNSA}#-#{ENV}# 
    collection: "keygen" 
    operation: insert-one
    write_concern:
      j: true
      w_timeout: 5000ms
    document_map: |
      root = @.filter(kv -> kv.key.has_prefix("kafka_")).map_each_key(key -> key.trim_prefix("kafka_"))
      root.value = this