apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bob_compare.yaml
patches:
- target:
    kind: ApplicationProfile
    name: replicaset-webapp-d87cdd796
  patch: |-
    - op: replace
      path: "/metadata/namespace"
      value: "mynamespace"
    - op: replace
      path: "/metadata/labels/kubescape.io~1workload-namespace"
      value: "mynamespace"
    - op: replace
      path: "/metadata/annotations/kubescape.io~1wlid"
      value: "wlid://cluster-mycluster/namespace-mynamespace/deployment-webapp"
    - op: replace
      path: "/spec/containers/0/endpoints/0/headers/Host"
      value:
      - "customerhost:8080"
