config:
  pluginsDir: /build/plugins

initContainers:
  - command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
    image: ghcr.io/kubebeam/kubescape-headlamp-plugin:latest ## you can specify a version such as 0.5.0-beta
    name: kubescape-plugin
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins

volumeMounts:
  - name: headlamp-plugins
    mountPath: /build/plugins

volumes:
  - name: headlamp-plugins
    emptyDir: {}