apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: metadata-api-tracing
spec:
  kprobes:
  - call: "tcp_sendmsg"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DAddr" # Monitor packets received from the metadata API
        values:
        - "169.254.169.254" 
      matchBinaries:
        - operator: "NotIn" 
          values:
          - "/usr/bin/kubelet"
          - "/usr/bin/dockerd"
          - "/usr/bin/containerd"
          - "/opt/cni/bin/cilium-cni" 
          - "/usr/bin/dumb-init"
          - "/nginx-ingress-controller"
          - "/main" 

