apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: metadata-api-tracing
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DAddr" 
        values:
        - "169.254.169.254" # Metadata API IP address
      matchBinaries:
        - operator: "NotIn" # Exclude system/Cilium components
          values:
          - "/usr/bin/kubelet"
          - "/usr/bin/dockerd"
          - "/usr/bin/containerd"
          - "/opt/cni/bin/cilium-cni" 
          # Add other known system binaries here if needed
    returnArg:
      index: 0
      type: "int"
    returnArgAction: "Post"

