apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-k8s-secrets-dump"
spec:
  kprobes:
  - call: "security_file_open"
    syscall: false
    return: false
    args:
    - index: 0
      type: "filename" # (struct file *) used for getting the path
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/var/run/secrets/" # Path to Kubernetes secrets