apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-symlinkat"
spec:
  kprobes:
  - call: "sys_symlinkat"
    syscall: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "int"
    - index: 2
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "/etc/kubernetes/pki/apiserver.key" 
        - "/home/ansible/.id_rsa_tmp"
    - matchActions:
      - action: Post
    - matchBinaries:
      - operator: "NotIn"
        values:
        - "/usr/bin/dumb-init"


