apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "log-file-deletions"
spec:
  kprobes:
  - call: "security_inode_unlink"
    syscall: false
    return: false
    args:
    - index: 0
      type: "filename" # (struct dentry *) used for getting the path
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/var/log/" # Kind
