cache:
    type: mem
    size: 512
perf-buffer-size: 1024
healthz: true
metrics: true
pprof: false
pyroscope: false
listen-addr: :3366

log:
    level: info
    # file: "/path/to/log/file.log"
    # aggregate:
    #     enabled: true
    #     flush-interval: "5s"
    # filters:
    #     libbpf: false
    #     in:
    #     msg:
    #         - SampleMessage1
    #         - SampleMessage2
    #     pkg:
    #         - package1
    #         - package2
    #     file:
    #         - file1.go
    #         - file2.go
    #     level:
    #         - warn
    #         - error
    #     regex:
    #         - ^pattern1
    #         - ^pattern2
    #     out:
    #     msg:
    #         - ExcludedMessage1
    #     pkg:
    #         - excludedPackage
    #     file:
    #         - excludedFile.go
    #     level:
    #         - debug
    #     regex:
    #         - ^excludedPattern
output:
    json:
        files:
            - stdout
    options:
        parse-arguments: true
        stack-addresses: false
        exec-env: false
        relative-time: true
        exec-hash: dev-inode
        sort-events: false
