apiVersion: apps/v1
kind: Deployment
metadata:
  name: stix-visualizer
  namespace: storm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stix-visualizer
  template:
    metadata:
      labels:
        app: stix-visualizer
    spec:
      containers:
      - name: stix-visualizer
        #image: ghcr.io/k8sstormcenter/cti-stix-visualizer:0.0.2
        image: entlein/cti-stix-visualizer:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          value: "redis-master.storm.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_KEY_PREFIX
          value: "tetra_bundle"
        - name: MONGODB_URI
          value: "mongodb://mongo-mongodb.honey.svc.cluster.local:27017"
        - name: LIGHTENINGROD
          value: "http://lighteningrod.storm.svc.cluster.local:8000"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3




---

apiVersion: v1
kind: Service
metadata:
  name: stix-visualizer
  namespace: storm
spec:
  selector:
    app: stix-visualizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP