apiVersion: v1
kind: Namespace
metadata:
  name: pacman
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman-rancher
  namespace: pacman
  annotations:
    iam.gke.io/gcp-service-account: "pacman-rancher@${PROJECT_ID}.iam.gserviceaccount.com" 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimi
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimi
  template:
    metadata:
      labels:
        app: minimi
    spec:
      serviceAccountName: pacman-rancher
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      automountServiceAccountToken: true
      containers:
      - name: minimi
        image: google/cloud-sdk:slim
        command: ["sleep","infinity"]
        imagePullPolicy: Always
        env:
        - name: KMS_PROJECT_ID
          value: "${PROJECT_ID}" # Replace with your actual GCP project ID
        - name: KMS_LOCATION
          value: "europe-west1" # Replace with your KMS location
        - name: KMS_KEY_RING
          value: "gkefederated${PROJECT_ID}" # Replace with your KMS key ring name
        - name: KMS_KEY_NAME
          value: "crypto_key"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minimi
  namespace: pacman
spec:
  selector:
    app: minimi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080