apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-monitoring
    etcd_cluster: pl-etcd
  name: pl-etcd
  namespace: pl
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
  - name: peer
    port: 2380
  publishNotReadyAddresses: true
  selector:
    app: pl-monitoring
    etcd_cluster: pl-etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pl-monitoring
    etcd_cluster: pl-etcd
  name: pl-etcd-client
  namespace: pl
spec:
  ports:
  - name: etcd-client
    port: 2379
  selector:
    app: pl-monitoring
    etcd_cluster: pl-etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pl-monitoring
    etcd_cluster: pl-etcd
  name: pl-etcd
  namespace: pl
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: pl-monitoring
      etcd_cluster: pl-etcd
  serviceName: pl-etcd
  template:
    metadata:
      labels:
        app: pl-monitoring
        etcd_cluster: pl-etcd
        plane: control
      name: pl-etcd
    spec:
      containers:
      - env:
        - name: INITIAL_CLUSTER_SIZE
          value: "3"
        - name: CLUSTER_NAME
          value: pl-etcd
        - name: ETCDCTL_API
          value: "3"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DATA_DIR
          value: /var/run/etcd
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "5"
        - name: ETCD_AUTO_COMPACTION_MODE
          value: revision
        image: gcr.io/pixie-oss/pixie-dev-public/etcd:3.5.9@sha256:e18afc6dda592b426834342393c4c4bd076cb46fa7e10fa7818952cae3047ca9
        lifecycle:
          preStop:
            exec:
              command:
              - /etc/etcd/scripts/prestop.sh
        livenessProbe:
          exec:
            command:
            - /etc/etcd/scripts/healthcheck.sh
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: etcd
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: server
        readinessProbe:
          exec:
            command:
            - /etc/etcd/scripts/healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        securityContext:
          capabilities:
            add:
            - NET_RAW
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/run/etcd
          name: etcd-data
        - mountPath: /etc/etcdtls/member/peer-tls
          name: member-peer-tls
        - mountPath: /etc/etcdtls/member/server-tls
          name: member-server-tls
        - mountPath: /etc/etcdtls/client/etcd-tls
          name: etcd-client-tls
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      - effect: NoExecute
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: arm64
      - effect: NoExecute
        key: kubernetes.io/arch
        operator: Equal
        value: arm64
      volumes:
      - name: member-peer-tls
        secret:
          secretName: etcd-peer-tls-certs
      - name: member-server-tls
        secret:
          secretName: etcd-server-tls-certs
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls-certs
      - emptyDir: {}
        name: etcd-data
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: pl-monitoring
  name: pl-etcd-pdb
  namespace: pl
spec:
  minAvailable: 51%
  selector:
    matchLabels:
      app: pl-monitoring
      etcd_cluster: pl-etcd
