# CE_NS_ENTER edge
apiVersion: v1
kind: Pod
metadata:
  name: nsenter-pod
  labels:
    app: kubehound-edge-test
spec:
  hostPID: true
  containers:
    - name: nsenter-pod
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/bash", "-c", "while true; do sleep 3000; done"]
      #command: ["nsenter -t 1 -a /bin/bash", "-c", "while true; do sleep 3000; done"]



