# CE_NET_ADMIN edge
apiVersion: v1
kind: Pod
metadata:
  name: netadmin-pod
  labels:
    app: kubehound-edge-test
spec:
  hostNetwork: true
  containers:
    - name: netadmin-pod
      #image: entlein/kh-verify:0.0.1
      image: ghcr.io/k8sstormcenter/lightening-kh-verify:latest
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
      command: [ "/bin/sh", "-c", "--" ]
      args: [
        "iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080 && \
         iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8080 && \
         mitmdump && sleep infinity"
      ]
