# CE_SYS_PTRACE edge
apiVersion: v1
kind: Pod
metadata:
  name: sys-ptrace-pod
  labels:
    app: kubehound-edge-test
spec:
  hostPID: true
  containers:
    - name: sys-ptrace-pod
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do sleep 3000; done"]
      securityContext:
        capabilities:
          add:
          - SYS_PTRACE
          - SYS_ADMIN