# EXPLOIT_HOST_WRITE edge
apiVersion: v1
kind: Pod
metadata:
  name: host-write-exploit-pod
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
    - name:  host-write-exploit-pod
      image: entlein/exploit-host-write:0.0.1
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /host/
        name: hostroot


  volumes:
    - name: hostroot
      hostPath:
        path: /etc/cron.d
