# EXPLOIT_HOST_WRITE edge
apiVersion: v1
kind: Pod
metadata:
  name: host-write-exploit-pod
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
    - name:  host-write-exploit-pod
      image: ghcr.io/k8sstormcenter/lightening-exploit-host-write:latest
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /host/
        name: hostroot


  volumes:
    - name: hostroot
      hostPath:
        path: /etc/cron.d
