apiVersion: v1
kind: Pod
metadata:
  name: kh-identity-impersonate
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
  - name: kubehound-identity-impersonate
    image: ghcr.io/k8sstormcenter/lightening-identity-impersonate:latest
    imagePullPolicy: Always