apiVersion: v1
kind: Pod
metadata:
  name: kh-identity-impersonate
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
  - name: kubehound-identity-impersonate
    image: entlein/identity-impersonate:0.0.1
    imagePullPolicy: Always