apiVersion: v1
kind: Pod
metadata:
  name: shared-process-namespace-pod
  labels:
    app: kubehound-edge-test
spec:
  shareProcessNamespace: true 
  containers:
  - name: nginx-container
    image: nginx:latest 
  - name: shell-container
    image: busybox:latest
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE 
    stdin: true
    tty: true
    command: ["/bin/sh", "-c"]
    args:
      - | 
        NGINX_PID=$(pgrep nginx| head -n 1);  
        head "/proc/$NGINX_PID/root/etc/nginx/nginx.conf";  
        sleep infinity 

