apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: partial
    kubescape.io/instance-id: apiVersion-v1/namespace-default/kind-Pod/name-webapp
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-honeycluster/namespace-default/pod-webapp
  labels:
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Pod
    kubescape.io/workload-name: webapp
    kubescape.io/workload-namespace: default
    kubescape.io/workload-resource-version: "982"
  name: pod-webapp
  namespace: default
  resourceVersion: "1"
  uid: a9d97746-91e3-4412-868d-1a73a2137650
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_RAW
    - SETUID
    endpoints:
    - direction: inbound
      endpoint: :30826/ping.php
      headers:
        Host:
        - 172.16.0.2:30826
      internal: false
      methods:
      - GET
    execs:
    - args:
      - /bin/ping
      - -c
      - "4"
      - 172.16.0.2
      path: /bin/ping
    - args:
      - /bin/sh
      - -c
      - ping -c 4 172.16.0.2
      path: /bin/sh
    identifiedCallStacks: null
    imageID: docker.io/amitschendel/ping-app@sha256:99fe0f297bbaeca1896219486de8d777fa46bd5b0cabe8488de77405149c524d
    imageTag: docker.io/amitschendel/ping-app:latest
    name: ping-app
    opens:
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/ld.so.cache
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libc-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libcap.so.2.44
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libresolv-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.7
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
    - flags:
      - O_RDONLY
      path: /var/www/html/ping.php
    rulePolicies: null
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - connect
    - dup2
    - execve
    - exit_group
    - fcntl
    - fstat
    - getcwd
    - getegid
    - geteuid
    - getgid
    - getpid
    - getppid
    - getrandom
    - getsockname
    - getsockopt
    - getuid
    - ioctl
    - lstat
    - mmap
    - mprotect
    - munmap
    - openat
    - pipe2
    - poll
    - prctl
    - prlimit64
    - read
    - recvmsg
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - select
    - sendto
    - setitimer
    - setsockopt
    - setuid
    - shutdown
    - socket
    - stat
    - times
    - vfork
    - wait4
    - write
    - writev
status: {}