apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
# CE_VAR_LOG_SYMLINK edge
apiVersion: v1
kind: ServiceAccount
metadata:
  name: varlog-sa
  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesploit-server
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesploit-server
  template:
    metadata:
      labels:
        app: kubesploit-server
    spec:
      serviceAccountName: varlog-sa
      containers:
      - name: kubesploit-server
        image: ghcr.io/k8sstormcenter/kubesploit-server:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: [" sleep infinity"]
        volumeMounts:
        - mountPath: /var/log/host
          name: nodelog
      volumes:
        - name: nodelog
          hostPath:
            path: /var/log
            type: Directory


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: demo
  name: read-logs
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes/log"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-read-logs
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-logs
subjects:
  - kind: ServiceAccount
    name: varlog-sa
    namespace: demo

