apiVersion: v1
kind: ServiceAccount
metadata:
  name: cap-checker
  namespace: storm

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: storm
  name: pod-executor
rules:
- apiGroups: [""] 
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-executor-binding
  namespace: storm
subjects:
- kind: ServiceAccount
  name: cap-checker 
  namespace: storm  
roleRef:
  kind: Role
  name: pod-executor
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-executor-binding
  namespace: storm
subjects:
- kind: ServiceAccount
  name: lightening
  namespace: storm  
roleRef:
  kind: Role
  name: pod-executor
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cap-checker
  labels:
    app: cap-checker
spec:
  selector:
    matchLabels:
      app: cap-checker
  template:
    metadata:
      labels:
        app: cap-checker
    spec:
      hostPID: true
      serviceAccountName: cap-checker
      containers:
      - name: cap-checker
        image: entlein/lightening:0.0.2
        command: ["/bin/bash", "-c"]
        args: ["sleep infinity"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-proc
          mountPath: /proc
          readOnly: true
        - name: host-tmp
          mountPath: /host/tmp
      volumes:
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-tmp
        hostPath:
          path: /tmp