apiVersion: softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: example-profile
spec:
  containers:
  - name: example-container
    policyByRuleId:
      "rule1":
        allowedProcesses:
        - "bash"
        - "cat"
        allowedContainer: true
    syscalls:
    - "new-syscall"