apiVersion: v1
data:
  clusterData: |
    {
      "serviceDiscovery": false,
      "vulnScanURL": "kubevuln:8080",
      "kubevulnURL": "kubevuln:8080",
      "kubescapeURL": "kubescape:8080",
      "clusterName": "honeycluster",
      "storage": true,
      "relevantImageVulnerabilitiesEnabled": true,
      "namespace": "honey",
      "imageVulnerabilitiesScanningEnabled": true,
      "postureScanEnabled": true,
      "otelCollector": false,
      "nodeAgent": "true",
      "maxImageSize": 5.36870912e+09,
      "maxSBOMSize": 2.097152e+07,
      "keepLocal": true,
      "scanTimeout": "5m",
      "vexGeneration": false,
      "useDefaultMatchers": false,
      "storeFilteredSbom": false,
      "continuousPostureScan": true,
      "relevantImageVulnerabilitiesConfiguration": "enable"
    }
kind: ConfigMap
metadata:
  labels:
    app: ks-cloud-config
    app.kubernetes.io/component: ks-cloud-config
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: kubescape
    kubescape.io/ignore: "true"
    kubescape.io/infra: config
    kubescape.io/tier: core
    tier: ks-control-plane
  name: ks-cloud-config
  namespace: honey
