nodeAgent:
  config:
    maxLearningPeriod: 5m
    learningPeriod: 2m
    updatePeriod: 1m
  env:
    - name: NodeName
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
capabilities:
  runtimeDetection: enable
alertCRD:
  installDefault: true
  scopeClustered: true
clusterName: honeycluster
ksNamespace: honey
excludeNamespaces: "kubescape,kube-system,kube-public,kube-node-lease,kubeconfig,gmp-system,gmp-public,honey,storm,lightening,cert-manager,openebs"