apiVersion: v1
kind: Namespace
metadata:
  name: pacman
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman-rancher
  namespace: pacman
  annotations:
    iam.gke.io/gcp-service-account: "<service-account-name>" 




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssrf-example
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssrf-example
  template:
    metadata:
      labels:
        app: ssrf-example
    spec:
      serviceAccountName: pacman-rancher
      automountServiceAccountToken: true
      containers:
      - name: ssrf-example
        image: ghcr.io/k8sstormcenter/ssrf-example:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ssrf-example
  namespace: pacman
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: ssrf-example
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080