apiVersion: v1
kind: Namespace
metadata:
  name: pacman
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman-rancher
  namespace: pacman
  annotations:
    iam.gke.io/gcp-service-account: "<service-account-name>" 




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: pacman-rancher
      automountServiceAccountToken: true
      containers:
      - name: user-service
        image: ghcr.io/k8sstormcenter/user-service:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: pacman
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "<your-ip>/32"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
  name: user-service-ingress
  namespace: pacman
spec:
  ingressClassName: "nginx"
  tls:
  - secretName: www-secret-gcp
    hosts:
      - "<service-url>"
  rules:
  - host: "<service-url>"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80