input:
  kafka:
    addresses: [ "${REDPANDA_HOSTS}" ]
    topics:
      - keygenapp
    consumer_group: "redpanda-connect-baselineapp"
  
pipeline:
  processors:
    - redis:
        url: "redis://${REDIS_HOST}"
        command: SADD
        args_mapping: 'root = [ "baselineapp", @kafka_key ]'

output:
  drop: {}
