---
apiVersion: v1
data:
  # Change this to your domain, if you have set up a domain and DNS rules for your cloud.
  PL_CLOUD_ADDR: "vzconn-service.plc.svc.cluster.local:51600"
  # Fill out a name for your cluster, otherwise it will be randomly generated.
  PL_CLUSTER_NAME: ""
  # Change this to your domain, if you have set up a domain and DNS rules for your cloud.
  PL_UPDATE_CLOUD_ADDR: "api-service.plc.svc.cluster.local:51200"
kind: ConfigMap
metadata:
  name: pl-cloud-config
  namespace: pl
---
apiVersion: v1
data:
  PL_CUSTOM_ANNOTATIONS: ""
  PL_CUSTOM_LABELS: ""
  PL_DISABLE_AUTO_UPDATE: "false"
  PL_ETCD_OPERATOR_ENABLED: "false"
  PL_MD_ETCD_SERVER: https://pl-etcd-client.pl.svc:2379
  PX_MEMORY_LIMIT: ""
  PX_MEMORY_REQUEST: ""
kind: ConfigMap
metadata:
  name: pl-cluster-config
  namespace: pl
---
apiVersion: v1
kind: Secret
metadata:
  name: pl-cluster-secrets
  namespace: pl
stringData:
  sentry-dsn: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: pl-deploy-secrets
  namespace: pl
stringData:
  # Fill this in with your deploy key from the Admin UI or CLI.
  deploy-key: ""
