apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-ce-sys-ptrace"
spec:
  kprobes:
  - call: "sys_ptrace"
    syscall: true
    args:
     - index: 2
       type: "int"
    selectors:
    - matchActions:
      - action: Post

