apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-iptables-mitm"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: "int" 
    - index: 1
      type: "file" 
    selectors:
    - matchArgs:
       - index: 1
         operator: "Prefix"
         values:
         - "/sbin/iptables"
         - "/usr/sbin/iptables"
         - "/usr/bin/mitmdump"


