apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: pod-pixie-operator-index-zxhdt
  namespace: px-operator
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/instance-id: apiVersion-v1/namespace-px-operator/kind-Pod/name-pixie-operator-index-zxhdt
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-px-operator/pod-pixie-operator-index-zxhdt
  labels:
    kubescape.io/workload-api-group: null
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Pod
    kubescape.io/workload-name: pixie-operator-index-zxhdt
    kubescape.io/workload-namespace: px-operator
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - CHOWN
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - NET_ADMIN
    - SETGID
    - SETPCAP
    - SETUID
    - SYS_ADMIN
    endpoints: null
    execs:
    - args:
      - /bin/grpc_health_probe
      - -addr=:50051
      path: /bin/grpc_health_probe
    - args:
      - /bin/opm
      - registry
      - serve
      - --database
      - /database/index.db
      path: /bin/opm
    identifiedCallStacks: null
    imageID: gcr.io/pixie-oss/pixie-prod/operator/bundle_index@sha256:1f69b7bb1ce9bd6b0898ae15bf6d17f07669c0958a964da973b3560f84cb9ba4
    imageTag: gcr.io/pixie-oss/pixie-prod/operator/bundle_index:0.0.1
    name: registry-server
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bin/grpc_health_probe
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bin/opm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /database/index.db
    - flags:
      - O_WRONLY
      - O_CREAT
      - O_CLOEXEC
      path: /dev/termination-log
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /dev/urandom
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/group
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/kernel/cap_last_cap
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/maps
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/setgroups
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/task/⋯/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/devices/system/cpu/online
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_NOFOLLOW
      - O_RDWR
      - O_CREAT
      - O_EXCL
      - O_CLOEXEC
      path: /tmp/db-*
    - flags:
      - O_EXCL
      - O_NOFOLLOW
      - O_CLOEXEC
      - O_RDWR
      - O_CREAT
      path: /var/tmp/etilqs_*
    - flags:
      - O_CLOEXEC
      - O_CREAT
      - O_EXCL
      - O_NOFOLLOW
      - O_RDWR
      path: /var/tmp/⋯
    rulePolicies:
      R0001:
        processAllowed:
        - grpc_health_pro
        - opm
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - clone3
    - close
    - close_range
    - connect
    - copy_file_range
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - faccessat2
    - fchdir
    - fchmodat
    - fchown
    - fchownat
    - fcntl
    - fsconfig
    - fsmount
    - fsopen
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - keyctl
    - listen
    - lstat
    - madvise
    - mkdirat
    - mknodat
    - mmap
    - mount
    - mprotect
    - mremap
    - munmap
    - nanosleep
    - newfstatat
    - open
    - open_tree
    - openat
    - openat2
    - pipe2
    - pivot_root
    - prctl
    - pread64
    - prlimit64
    - pwrite64
    - read
    - readlink
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendfile
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setns
    - setsid
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - stat
    - statfs
    - statx
    - symlinkat
    - tgkill
    - tkill
    - umask
    - umount2
    - uname
    - unlink
    - unlinkat
    - unshare
    - write
    - writev
