apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: job-23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
  namespace: px-operator
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/instance-id: apiVersion-batch/v1/namespace-px-operator/kind-Job/name-23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-px-operator/job-23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
  labels:
    kubescape.io/workload-api-group: batch
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Job
    kubescape.io/workload-name: 23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
    kubescape.io/workload-namespace: px-operator
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    endpoints: null
    execs:
    - args:
      - /bin/opm
      - alpha
      - bundle
      - extract
      - -m
      - /bundle/
      - -n
      - px-operator
      - -c
      - 23864b92b5c58447045dc434f6e35f4f5a3751099701da69e43081a6b7b7a0b
      - -z
      path: /bin/opm
    identifiedCallStacks: null
    imageID: quay.io/operator-framework/opm@sha256:d999588bd4e9509ec9e75e49adfb6582d256e9421e454c7fb5e9fe57e7b1aada
    imageTag: quay.io/operator-framework/opm@sha256:d999588bd4e9509ec9e75e49adfb6582d256e9421e454c7fb5e9fe57e7b1aada
    name: extract
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bin/opm
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bundle/manifests
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /bundle/manifests/crd.yaml
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bundle/manifests/csv.yaml
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bundle/metadata
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /bundle/metadata/annotations.yaml
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/token
    rulePolicies:
      R0001:
        processAllowed:
        - opm
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - clone3
    - close
    - close_range
    - connect
    - copy_file_range
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - faccessat2
    - fchdir
    - fchmodat
    - fchown
    - fchownat
    - fcntl
    - fsconfig
    - fsmount
    - fsopen
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - keyctl
    - listen
    - lstat
    - madvise
    - mkdirat
    - mknodat
    - mmap
    - mount
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - open_tree
    - openat
    - openat2
    - pipe2
    - pivot_root
    - prctl
    - pread64
    - prlimit64
    - read
    - readlink
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendfile
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsid
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - stat
    - statfs
    - statx
    - symlinkat
    - tgkill
    - tkill
    - umask
    - umount2
    - uname
    - unlinkat
    - write
    - writev
