apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: job-cert-provisioner-job
  namespace: pl
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    endpoints: null
    execs:
    - args:
      - /app/src/utils/cert_provisioner/cert_provisioner
      path: /app/src/utils/cert_provisioner/cert_provisioner
    identifiedCallStacks: null
    imageID: gcr.io/pixie-oss/pixie-prod/vizier-cert_provisioner_image@sha256:2e00396429096505cf11cb31e62e447a45bbd2497089cc41c78955a24b8e3558
    imageTag: gcr.io/pixie-oss/pixie-prod/vizier-cert_provisioner_image:0.14.15
    name: provisioner
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /app/src/utils/cert_provisioner/cert_provisioner.runfiles/px/src/utils/cert_provisioner/cert_provisioner_/cert_provisioner
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/*
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/*/task/*/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/*
    rulePolicies:
      R0001:
        processAllowed:
        - cert_provisione
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - access
    - arch_prctl
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - exit
    - exit_group
    - faccessat2
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - ioctl
    - madvise
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - tgkill
    - tkill
    - uname
    - write
