apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: replicaset-vizier-query-broker-765664495f
  namespace: pl
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-pl/kind-ReplicaSet/name-vizier-query-broker-765664495f
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-pl/deployment-vizier-query-broker
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: vizier-query-broker
    kubescape.io/workload-namespace: pl
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - FOWNER
    - NET_ADMIN
    endpoints: null
    execs:
    - args:
      - /app/src/vizier/services/query_broker/query_broker
      path: /app/src/vizier/services/query_broker/query_broker
    identifiedCallStacks: null
    imageID: gcr.io/pixie-oss/pixie-prod/vizier-query_broker_server_image@sha256:d20204368b519a1bf9a04662ea276b70522a45837199a32791f01993b2dc5426
    imageTag: gcr.io/pixie-oss/pixie-prod/vizier-query_broker_server_image:0.14.15
    name: app
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /app/src/vizier/services/query_broker/query_broker.runfiles/px/src/vizier/services/query_broker/query_broker_/query_broker
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/client.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/client.key
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/server.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/server.key
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/hosts
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/liblzma.so.5.4.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libm.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libresolv.so.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libz.so.1.2.13
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/devices/system/cpu/online
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /usr/lib/x86_64-linux-gnu/libunwind.so.8.0.1
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/token
    rulePolicies:
      R0001:
        processAllowed:
        - query_broker
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - connect
    - dup2
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - faccessat2
    - fchdir
    - fchmodat
    - fchown
    - fchownat
    - fcntl
    - fork
    - fsconfig
    - fsmount
    - fsopen
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - keyctl
    - listen
    - madvise
    - membarrier
    - mincore
    - mkdirat
    - mknodat
    - mmap
    - mount
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - open_tree
    - openat
    - openat2
    - pipe
    - pipe2
    - pivot_root
    - poll
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendto
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsid
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - socketpair
    - stat
    - statfs
    - statx
    - symlinkat
    - tgkill
    - tkill
    - umask
    - umount2
    - uname
    - unlinkat
    - wait4
    - write
    - writev
