apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: replicaset-vizier-operator
  namespace: px-operator
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_ADMIN
    endpoints:
    - direction: outbound
      endpoint: :8222/
      headers:
        Accept-Encoding:
          - gzip
        Host:
          - 10-42-1-11.pl.pod.cluster.local:8222
      internal: false
      methods:
        - GET
    execs:
    - args:
      - /app/src/operator/operator
      path: /app/src/operator/operator
    identifiedCallStacks: null
    name: app
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /app/src/operator/operator.runfiles/px/src/operator/operator_/operator
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs/ca-certificates.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libm.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libresolv.so.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/⋯/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/token
    rulePolicies:
      R0001:
        processAllowed:
        - operator
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone3
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - exit
    - faccessat2
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - ioctl
    - listen
    - lseek
    - madvise
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - poll
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendmmsg
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - tgkill
    - tkill
    - uname
    - write
