apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: replicaset-olm-operator
  namespace: olm
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - NET_ADMIN
    endpoints:
    - direction: inbound
      endpoint: :8080/healthz
      headers:
        Connection:
          - close
        Host:
          - 10.42.0.20:8080
      internal: false
      methods:
        - GET
    execs:
    - args:
      - /bin/olm
      - --namespace
      - olm
      - --writeStatusName
      path: /bin/olm
    identifiedCallStacks: null
    imageID: quay.io/operator-framework/olm@sha256:1b6002156f568d722c29138575733591037c24b4bfabc67946f268ce4752c3e6
    imageTag: quay.io/operator-framework/olm@sha256:1b6002156f568d722c29138575733591037c24b4bfabc67946f268ce4752c3e6
    name: olm-operator
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: \1*
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/*/task/*/fd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/kernel/cap_last_cap
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/*
    rulePolicies:
      R0001:
        processAllowed:
        - olm
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - bind
    - capget
    - capset
    - chdir
    - clone
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - exit
    - faccessat2
    - fchown
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - listen
    - madvise
    - mmap
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - read
    - readlinkat
    - recvfrom
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - statfs
    - tgkill
    - tkill
    - uname
    - write
