apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: replicaset-vizier-metadata
  namespace: pl
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_ADMIN
    endpoints: null
    execs:
    - args:
      - /app/src/vizier/services/metadata/metadata
      path: /app/src/vizier/services/metadata/metadata
    identifiedCallStacks: null
    imageID: docker.io/entlein/vizier-metadata_server_image@sha256:7b3800dd7993c134bc0b864cee449c61eafc88e3336b99dcf2d36acbba665b2f
    imageTag: docker.io/entlein/vizier-metadata_server_image:2025-06-19_09-51-27.876_UTC
    name: app
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /app/src/vizier/services/metadata/metadata.runfiles/px/src/vizier/services/metadata/metadata_/metadata
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/⋯
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/⋯
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x⋯_⋯-linux-gnu/⋯
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/⋯/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/⋯
    rulePolicies:
      R0001:
        processAllowed:
        - metadata
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone3
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - faccessat2
    - fcntl
    - fdatasync
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - ioctl
    - listen
    - madvise
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - tgkill
    - tkill
    - uname
    - write
