apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: replicaset-vizier-metadata-5f47d4fcfb
  namespace: pl
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-pl/kind-ReplicaSet/name-vizier-metadata-5f47d4fcfb
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-pl/deployment-vizier-metadata
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: vizier-metadata
    kubescape.io/workload-namespace: pl
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_ADMIN
    endpoints: null
    execs:
    - args:
      - /app/src/vizier/services/metadata/metadata
      path: /app/src/vizier/services/metadata/metadata
    identifiedCallStacks: null
    imageID: gcr.io/pixie-oss/pixie-prod/vizier-metadata_server_image@sha256:3c2e07eeb209f53c982724173457c8650301e4b36e29d3d93e7196c6e56a7cc5
    imageTag: gcr.io/pixie-oss/pixie-prod/vizier-metadata_server_image:0.14.15
    name: app
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /app/src/vizier/services/metadata/metadata.runfiles/px/src/vizier/services/metadata/metadata_/metadata
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/client.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/client.key
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/server.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /certs/⋯/server.key
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libm.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libresolv.so.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/ca.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/token
    rulePolicies:
      R0001:
        processAllowed:
        - metadata
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone3
    - close
    - close_range
    - connect
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - faccessat2
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - ioctl
    - listen
    - madvise
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe2
    - prctl
    - pread64
    - prlimit64
    - read
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - tgkill
    - tkill
    - uname
    - write
