apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: replicaset-vizier-operator-7648ff4c7b
  namespace: px-operator
  annotations:
    kubescape.io/completion: complete
    kubescape.io/status: completed
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-px-operator/kind-ReplicaSet/name-vizier-operator-7648ff4c7b
    kubescape.io/wlid: wlid://cluster-bobexample/namespace-px-operator/deployment-vizier-operator
  labels:
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: vizier-operator
    kubescape.io/workload-namespace: px-operator
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_ADMIN
    endpoints: 
    - direction: outbound
      endpoint: :8222/
      headers:
        Accept-Encoding:
          - gzip
        Host:
          - 10-42-0-26.pl.pod.cluster.local:8222
      internal: false
      methods:
        - GET
    execs:
    - args:
      - /app/src/operator/operator
      path: /app/src/operator/operator
    identifiedCallStacks: null
    imageID: gcr.io/pixie-oss/pixie-prod/operator-operator_image@sha256:f596c0293ca825c22beb316a10ac6999ee28abfef260609bdb2909bd470095d7
    imageTag: gcr.io/pixie-oss/pixie-prod/operator-operator_image:0.1.7
    name: app
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /app/src/operator/operator.runfiles/px/src/operator/operator_/operator
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs/ca-certificates.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libc.so.6
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libm.so.6
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /lib/x86_64-linux-gnu/libresolv.so.2
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/ca.crt
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/run/secrets/kubernetes.io/serviceaccount/⋯/token
    rulePolicies:
      R0001:
        processAllowed:
        - operator
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - clone3
    - close
    - close_range
    - connect
    - copy_file_range
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - faccessat2
    - fchdir
    - fchmodat
    - fchown
    - fchownat
    - fcntl
    - fsconfig
    - fsmount
    - fsopen
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getgid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - keyctl
    - listen
    - lseek
    - lstat
    - madvise
    - mkdirat
    - mknodat
    - mmap
    - mount
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open
    - open_tree
    - openat
    - openat2
    - pipe2
    - pivot_root
    - poll
    - prctl
    - pread64
    - prlimit64
    - read
    - readlink
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendfile
    - sendmmsg
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsid
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - stat
    - statfs
    - statx
    - symlinkat
    - tgkill
    - tkill
    - umask
    - umount2
    - uname
    - unlinkat
    - write
    - writev
