apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-ce-priv-mount"
spec:
  kprobes:
  - call: "sys_mount"
    syscall: true
    args:
    - index: 0
      type:  "string"
    - index: 1
      type:  "string"


