apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-ce-var-log-symlink"
spec:
  kprobes:
  - call: "sys_symlinkat"
    syscall: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "int"
    - index: 2
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/"
      - index: 2
        operator: "Equal"
        values:
        - "/host/var/log/root_link"
      matchActions:
      - action: Post  

#{"process_kprobe":{"process":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjA5NTc5OTYxNTA0MzM6MzQ4MjM1", "pid":348235, "uid":0, "cwd":"/", "binary":"/usr/bin/ln", "arguments":"-s / /host/var/log/root_link", "flags":"execve rootcwd clone", "start_time":"2025-01-30T21:55:42.414435484Z", "auid":4294967295, "pod":{"namespace":"default", "name":"priv-mount-pod", "container":{"id":"containerd://19c87fc8a8178532b23cfcabf7dde04edd423a1597a03ef883ef766384304cae", "name":"priv-mount-pod", "image":{"id":"docker.io/library/ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab", "name":"docker.io/library/ubuntu:latest"}, "start_time":"2025-01-30T21:55:02Z", "pid":78}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"priv-mount-pod", "workload_kind":"Pod"}, "docker":"19c87fc8a8178532b23cfcabf7dde04", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjA5NTc5OTQxOTQ4MzU6MzQ4MjI5", "refcnt":1, "tid":348235, "in_init_tree":false}, "parent":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjA5NTc5OTQxOTQ4MzU6MzQ4MjI5", "pid":348229, "uid":0, "cwd":"/", "binary":"/bin/bash", "arguments":"-c \"ln -s / /host/var/log/root_link  && echo SUCCESS1\" /dev/null", "flags":"execve rootcwd clone", "start_time":"2025-01-30T21:55:42.412479996Z", "auid":4294967295, "pod":{"namespace":"default", "name":"priv-mount-pod", "container":{"id":"containerd://19c87fc8a8178532b23cfcabf7dde04edd423a1597a03ef883ef766384304cae", "name":"priv-mount-pod", "image":{"id":"docker.io/library/ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab", "name":"docker.io/library/ubuntu:latest"}, "start_time":"2025-01-30T21:55:02Z", "pid":73}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"priv-mount-pod", "workload_kind":"Pod"}, "docker":"19c87fc8a8178532b23cfcabf7dde04", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjA5NTc5NTQ4NzgzODM6MzQ4MjIw", "tid":348229, "in_init_tree":false}, "function_name":"__x64_sys_symlinkat", "args":[{"string_arg":"/"}, {"int_arg":-100}, {"string_arg":"/host/var/log/root_link"}], "action":"KPROBE_ACTION_POST", "policy_name":"detect-ce-var-log-symlink", "return_action":"KPROBE_ACTION_POST"}, "node_name":"honeycluster-control-plane", "time":"2025-01-30T21:55:42.415174873Z"}