apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-ce-umh-core-pattern"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    return: true
    args:
    - index: 0
      type: "file" # (struct file *) used for getting the path
    - index: 1
      type: "int" # 0x04 is MAY_READ, 0x02 is MAY_WRITE
    returnArg:  # Return: Return 0 if the hook is successful and permission is granted.
      index: 0
      type: "int"
    returnArgAction: "Post"
    selectors:
    - matchArgs:      
      - index: 0
        operator: "Prefix"
        values:
         - "/proc/sys/kernel" # Do NOT use this on the host_ns, it crashes tetragon...
         - "/sysproc" #TODO: this is what the user defines as local mountpoint for the /proc fs , need solution to make this dynamic
      - index: 1
        operator: "Equal"
        values:
        - "2"
        - "4"
        - "6"
      matchNamespaces:
        - namespace: "Pid"
          operator: "NotIn"
          values:
          - "host_ns"
