apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-ce-nsenter"
spec:
  kprobes:
  - call: "sys_setns"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "int" # nstype



# #  The setns() system call allows the calling thread to move into
#        different namespaces.  The fd argument is one of the following:

#        •  a file descriptor referring to one of the magic links in a
#           /proc/pid/ns/ directory (or a bind mount to such a link);

#        •  a PID file descriptor (see pidfd_open(2)).

#        The nstype argument is interpreted differently in each case.
# On success, setns() returns 0.  On failure, -1 is returned and
#        errno is set to indicate the error.
# https://man7.org/linux/man-pages/man2/setns.2.html

