apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-exploit-host-write
spec:
  kprobes:
  - call: "sys_write"  # Capture writes
    syscall: true
    args:
      - index: 0 #file descriptor
        type: "int"
      - index: 1 # char_buf
        type: "char_buf"
        returnCopy: true
        sizeArgIndex: 2
      - index: 2 # count
        type: "int"
    selectors:
     - matchBinaries:
        - operator: "In"
          values: 
            - "/bin/sh"
            - "/bin/bash"
       matchNamespaces:
        - namespace: "Pid"
          operator: "NotIn"
          values:
            - "host_ns"   
       matchArgs:
        - index: 0
          operator: "Postfix"
          values:
            - "breakout"

  - call: "sys_fsync"           
    syscall: true
    args:
      - index: 0  # fd
        type: "int"
    selectors:
    - matchBinaries:
        - operator: "In"
          values: 
            - "/bin/sh"
            - "/bin/bash"
      matchNamespaces:
        - namespace: "Pid"
          operator: "NotIn"
          values:
            - "host_ns"


  # - call: "sys_fdatasync"     
  #   syscall: true
  #   args:
  #     - index: 0  # fd
  #       type: "int"
  #   selectors:
  #   - matchBinaries:
  #       - operator: "In"
  #         values: 
  #           - "/bin/sh"
  #           - "/bin/bash"
  #     matchNamespaces: #only if we are not in host_ns
  #       - namespace: "Pid"
  #         operator: "NotIn"
  #         values:
  #           - "host_ns"
  #     matchActions:
  #       - action: "Post"

  - call: "sys_openat" 
    syscall: true
    args:
    - index: 0
      type: "int"   
    - index: 1
      type: "string"   
    - index: 2
      type: "int"    
    selectors:
      - matchArgs:
          - index: 1
            operator: "Equal"
            values:
              - "/host/etc/cron.d/breakout"
  
