apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-exploit-host-read
spec:
  kprobes:
  - call: "sys_openat" 
    syscall: true
    args:
    - index: 0
      type: "int"   # dfd
    - index: 1
      type: "string"   # The file path
    - index: 2
      type: "int"     # Flags (O_RDONLY, etc.)
    selectors:
    - matchArgs:
        - index: 1
          operator: "Equal" # Use "In" for flexibility
          values:
            - "/proc/1/status"   
            - "/proc/1/mem"   
        # - index: 2                      # Flags
        #   operator: "Equal"             # Exact match needed for the flag
        #   values: ["00000000"]         # 0 = O_RDONLY (Read-only flag, adjust if necessary)
      matchNamespaces:  # Only match if occuring in a container
        - namespace: "Pid"
          operator: "NotIn"
          values:
            - "host_ns"


#{"process_kprobe":{"process":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjI3MTAwMzIzMjY2NTQ6MzMwMTMw", "pid":330130, "uid":0, "cwd":"/", "binary":"/usr/bin/grep", "arguments":"-Ev Name:\\s+(find|xargs|cat) /proc/1/status /proc/10/status /proc/11/status /proc/12/status /proc/13/status /proc/14/status", "flags":"execve rootcwd clone inInitTree", "start_time":"2025-01-07T16:45:29.314405856Z", "auid":4294967295, "pod":{"namespace":"default", "name":"kh-exploit-host-path-read", "container":{"id":"containerd://af705e077e7f2fffdd3aff9ad2dc9da3fb4eeee8cc30b0108b784f6ba2232ddf", "name":"procdump-container", "image":{"id":"docker.io/entlein/exploit-host-read@sha256:6011b79586ee9a153d1583e1b3039c6226e03a3e77521e16fd105d7a52471a42", "name":"docker.io/entlein/exploit-host-read:0.0.1"}, "start_time":"2025-01-07T16:45:29Z", "pid":15}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"kh-exploit-host-path-read", "workload_kind":"Pod"}, "docker":"af705e077e7f2fffdd3aff9ad2dc9da", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjI3MTAwMjk0NTYxNjg6MzMwMTI3", "refcnt":1, "tid":330130, "in_init_tree":true}, "parent":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjI3MTAwMjk0NTYxNjg6MzMwMTI3", "pid":330127, "uid":0, "cwd":"/", "binary":"/usr/bin/xargs", "arguments":"grep -Ev Name:\\s+(find|xargs|cat)", "flags":"execve rootcwd clone inInitTree", "start_time":"2025-01-07T16:45:29.311535130Z", "auid":4294967295, "pod":{"namespace":"default", "name":"kh-exploit-host-path-read", "container":{"id":"containerd://af705e077e7f2fffdd3aff9ad2dc9da3fb4eeee8cc30b0108b784f6ba2232ddf", "name":"procdump-container", "image":{"id":"docker.io/entlein/exploit-host-read@sha256:6011b79586ee9a153d1583e1b3039c6226e03a3e77521e16fd105d7a52471a42", "name":"docker.io/entlein/exploit-host-read:0.0.1"}, "start_time":"2025-01-07T16:45:29Z", "pid":12}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"kh-exploit-host-path-read", "workload_kind":"Pod"}, "docker":"af705e077e7f2fffdd3aff9ad2dc9da", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MjI3MTAwMjgxODY1NDQ6MzMwMTI1", "tid":330127, "in_init_tree":true}, "function_name":"__x64_sys_openat", "args":[{"int_arg":-100}, {"string_arg":"/proc/1/status"}, {"int_arg":256}], "action":"KPROBE_ACTION_POST", "policy_name":"detect-exploit-host-read", "return_action":"KPROBE_ACTION_POST"}, "node_name":"honeycluster-control-plane", "time":"2025-01-07T16:45:29.315493648Z"}