apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-share-ps-namespace"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
      - index: 0
        type: "int"
      - index: 1
        type: "string"
    selectors:
    - matchArgs:      
      - index: 1
        operator: "Prefix"
        values: #lets assume most containers dont spawn more than 20 processes, for nginx this is actually not correct
         - "/proc/1/root" 
         - "/proc/2/root" 
         - "/proc/3/root" 
         - "/proc/4/root" 
         - "/proc/5/root" 
         - "/proc/6/root" 
         - "/proc/7/root" 
         - "/proc/8/root" 
         - "/proc/9/root" 
         - "/proc/10/root"
         - "/proc/11/root"
         - "/proc/12/root"
         - "/proc/13/root"
         - "/proc/14/root"
         - "/proc/15/root"
         - "/proc/16/root"
         - "/proc/17/root"
         - "/proc/18/root"
         - "/proc/19/root"
         - "/proc/20/root"
      matchNamespaces:
        - namespace: "Pid"
          operator: "NotIn"
          values:
          - "host_ns"