apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-share-ps-namespace"
spec:
  kprobes:
  - call: "sys_openat"
    syscall: true
    args:
      - index: 0
        type: "int"
      - index: 1
        type: "string"
    selectors:
    - matchArgs:      
      - index: 1
        operator: "Prefix"
        values: #lets assume most containers dont spawn more than 20 processes, for nginx this is actually not correct
         - "/proc/1/root" 
         - "/proc/2/root" 
         - "/proc/3/root" 
         - "/proc/4/root" 
         - "/proc/5/root" 
         - "/proc/6/root" 
         - "/proc/7/root" 
         - "/proc/8/root" 
         - "/proc/9/root" 
         - "/proc/10/root"
         - "/proc/11/root"
         - "/proc/12/root"
         - "/proc/13/root"
         - "/proc/14/root"
         - "/proc/15/root"
         - "/proc/16/root"
         - "/proc/17/root"
         - "/proc/18/root"
         - "/proc/19/root"
         - "/proc/20/root"
      matchNamespaces:
        - namespace: "Pid"
          operator: "NotIn"
          values:
          - "host_ns"

#{"process_kprobe":{"process":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6OTc2MjIwMTYzMDQ5Nzc6NjEwNDU2", "pid":610456, "uid":0, "cwd":"/", "binary":"/bin/head", "arguments":"/proc/7/root/etc/nginx/nginx.conf", "flags":"execve rootcwd clone", "start_time":"2025-01-17T12:55:11.916719609Z", "auid":4294967295, "pod":{"namespace":"default", "name":"shared-process-namespace-pod", "container":{"id":"containerd://cab9de0a6b7de6b7a33b5b56c49a6fc4a1bdb7c7b720ae023ac065f8056bda7b", "name":"shell-container", "image":{"id":"docker.io/library/busybox@sha256:a5d0ce49aa801d475da48f8cb163c354ab95cab073cd3c138bd458fc8257fbf1", "name":"docker.io/library/busybox:latest"}, "start_time":"2025-01-17T12:55:11Z", "pid":66}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"shared-process-namespace-pod", "workload_kind":"Pod"}, "docker":"cab9de0a6b7de6b7a33b5b56c49a6fc", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6OTc2MjIwMTEwODc0MDg6NjEwNDM3", "tid":610456, "in_init_tree":false}, "parent":{"exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6OTc2MjIwMTEwODc0MDg6NjEwNDM3", "pid":610437, "uid":0, "cwd":"/", "binary":"/bin/sh", "arguments":"-c \"NGINX_PID=$(pgrep nginx| head -n 1); \nhead \"/proc/$NGINX_PID/root/etc/nginx/nginx.conf\"; \nsleep infinity \n\"", "flags":"execve rootcwd clone", "start_time":"2025-01-17T12:55:11.911502063Z", "auid":4294967295, "pod":{"namespace":"default", "name":"shared-process-namespace-pod", "container":{"id":"containerd://cab9de0a6b7de6b7a33b5b56c49a6fc4a1bdb7c7b720ae023ac065f8056bda7b", "name":"shell-container", "image":{"id":"docker.io/library/busybox@sha256:a5d0ce49aa801d475da48f8cb163c354ab95cab073cd3c138bd458fc8257fbf1", "name":"docker.io/library/busybox:latest"}, "start_time":"2025-01-17T12:55:11Z", "pid":54}, "pod_labels":{"app":"kubehound-edge-test"}, "workload":"shared-process-namespace-pod", "workload_kind":"Pod"}, "docker":"cab9de0a6b7de6b7a33b5b56c49a6fc", "parent_exec_id":"aG9uZXljbHVzdGVyLWNvbnRyb2wtcGxhbmU6OTc2MTk0NTUzNDA5MDg6NjEwMjc3", "tid":610437, "in_init_tree":false}, "function_name":"__x64_sys_openat", "args":[{"int_arg":-100}, {"string_arg":"/proc/7/root/etc/nginx/nginx.conf"}], "action":"KPROBE_ACTION_POST", "policy_name":"detect-share-ps-namespace", "return_action":"KPROBE_ACTION_POST"}, "node_name":"honeycluster-control-plane", "time":"2025-01-17T12:55:11.917486072Z"}
