apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-talos
  annotations:
    openebs.io/cas-type: local
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  basePath: "/tmp/openebs/local"