name: Build and push webapp and tampered webapp
on:
  push:
    branches:
      - 162-write-bob-testscript-for-anyone-to-contribute-a-bob-for-the-pingapps
    




env:
  REGISTRY: ghcr.io
  IMAGE_NAME: k8sstormcenter/webapp
  IMAGE_NAME_BOB: k8sstormcenter/bobapp




jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=match,pattern=\d.\d.\d.*
            type=sha

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: ./traces/kubescape-verify/attacks/bobprofile
          file: ./traces/kubescape-verify/attacks/bobprofile/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BOB }}:latest

      # - name: Build and push 
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./traces/kubescape-verify/attacks/webapp
      #     file: ./traces/kubescape-verify/attacks/webapp/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # - name: Build and push 
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./traces/kubescape-verify/attacks/webapp_t
      #     file: ./traces/kubescape-verify/attacks/webapp_t/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-t:latest

