name: Build and push the Hive Sentinel
on:
  push:
    branches:
      - main
    paths:
      - 'mywebapp-chart/**'
      - '.github/workflows/publish-oci-helmchart.yaml'



  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and push'
        required: true
        default: 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: k8sstormcenter/hivesentinel

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.event.inputs.branch || github.ref_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ github.head_ref || github.ref_name }}
            sha-${{ github.sha }}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./analysis/hive_sentinel
          file: ./analysis/hive_sentinel/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  cleanup-pr-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build-and-push-image
    permissions:
      packages: write
    steps:
      - name: Delete image for merged PR
        uses: actions/delete-package-versions@v4
        with:
          package-name: hivesentinel
          package-type: container
          min-versions-to-keep: 0
          delete-only-untagged-versions: false
          ignore-versions: latest
