name: Build and push Kubesploit
on:
  push:
    branches:
      - main
  pull_request:



env:
  REGISTRY: ghcr.io
  IMAGE_NAME: k8sstormcenter/kubesploit


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=match,pattern=\d.\d.\d.*
            type=sha

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: ./attacks/kubesploit
          file: ./attacks/kubesploit/Dockerfile_agent
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-agent:latest

      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: ./attacks/kubesploit
          file: ./attacks/kubesploit/Dockerfile_server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-server:latest

