apiVersion: apps/v1
kind: Deployment
metadata:
  name: syscall-demo
  labels:
    app: syscall-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syscall-demo
  template:
    metadata:
      labels:
        app: syscall-demo
    spec:
      containers:
      - name: syscall-demo
        image: entlein/syscall-demo:latest
